name: Build EPUB

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出源码
        uses: actions/checkout@v4

      - name: 设置 Node.js v10
        uses: actions/setup-node@v4
        with:
          node-version: '10'

      - name: 安装 Calibre
        run: |
          sudo apt-get update
          sudo apt-get install -y calibre

      - name: 安装 GitBook 和绘图依赖
        run: |
          npm install -g gitbook-cli
          npm install -g svgexport

      - name: 安装插件并生成 EPUB
        run: |
          gitbook install
          gitbook epub ./ ./FlutterBook.epub

      - name: 提取生成的 EPUB 文件
        uses: actions/upload-artifact@v4
        with:
          name: FlutterBook-EPUB
          path: ./FlutterBook.epub
